name: Guilherme Rossato
description: A handmade blog about developing things in practice
timezone: America/Sao_Paulo
markdown: redcarpet
collections:
  blog:
    output: true
    permalink: /posts/:title//
gems:
  - jekyll-redirect-from